apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: nats
spec:
  project: default
  source:
    chart: nats/nats
    repoURL: https://nats-io.github.io/k8s/helm/charts/
    targetRevision: HEAD
    helm:
      releaseName: 1.16.1
      valueFiles:
        - values.yaml
  destination:
    server: "https://dev.nabhan.xyz:6443"
    namespace: nats
