apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: argocd
spec:
  project: default
  source:
    chart: nats
    repoURL: https://nats-io.github.io/k8s/helm/charts/
    targetRevision: 0.17.1
    helm:
      releaseName: nats
      valueFiles:
        - values.yaml
  destination:
    server: "https://dev.nabhan.xyz:6443"
    namespace: nats
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
